LabPPW2017/LabPPW2017/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import lab02.urls as lab02
from lab02.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^lab02/', include(lab02, namespace='lab02')),
	url(r'^$', index),
]

lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import index, add_friend, validate_npm,delete_friend,friend_list,data_friend,get_friend_detail,get_data_user_view
urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add-friend/$', add_friend, name='add-friend'),
	url(r'^validate-npm/$', validate_npm, name='validate-npm'),
	url(r'^get-friend-list/$', friend_list, name='get-friend-list'),
	url(r'^get-friend-list/delete-friend/(?P<friend_id>[0-9]+)/$',delete_friend, name='delete-friend'),
	url(r'^data-friend/$', data_friend, name='data-friend'),
	url(r'^get-friend-list/get-friend-detail/(?P<friend_id>[0-9]+)/$', get_friend_detail, name='get-friend-detail'),
	url(r'^get-data-user/$', get_data_user_view, name='get-data-user'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
from lab_4.views import index
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
	url(r'^lab-2/', include(lab_2,namespace='lab-2')),
	url(r'^lab-2-addon/', include(lab_2_addon,namespace='lab-2-addon')),
	url(r'^$',RedirectView.as_view(url='/lab-4/',permanent='true'),name='index'),
	url(r'^lab-3/', include(lab_3,namespace='lab-3')),
    url(r'^lab-4/', include(lab_4, namespace='lab-4')),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    url(r'^lab-8/', include(lab_8, namespace='lab-8')),
    url(r'^lab-9/', include(lab_9, namespace='lab-9')),
    url(r'^lab-10/', include(lab_10, namespace='lab-10')),
]

lab_7/models.py
from django.db import models

class Friend(models.Model):
	friend_name = models.CharField(max_length=400)
	npm = models.CharField(max_length=250)
	alamat = models.CharField(max_length=400)
	kode_pos = models.CharField(max_length=400)
	kota_lahir = models.CharField(max_length=400)
	tanggal_lahir = models.CharField(max_length=400)
	added_at = models.DateField(auto_now_add=True)

lab_7/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from .models import Friend
from lab_9.csui_helper import get_mahasiswa_list, get_data_user, get_client_id
import os
import json
import requests
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


API_MAHASISWA = "https://api.cs.ui.ac.id/siakngcs/mahasiswa/"
response = {}
def index(request):
    if 'user_login' in request.session:
        response['author'] = request.session['user_login']
        response['kode_identitas'] = request.session['kode_identitas']
        response['connected'] = True
        response['name'] = 'Muhammad Ilham Peruzzi'
        access_token = request.session['access_token']
        mahasiswa_list = get_mahasiswa_list(access_token)
        friend_list = Friend.objects.all()
        page = request.GET.get('page', 1)
        paginator = Paginator(mahasiswa_list, 10)
        mahasiswa_list = paginator.page(page)
        response['mahasiswa_list'] = mahasiswa_list
        response['friend_list'] = friend_list
        html = 'lab_7/lab_7.html'
        return render(request, html, response)
    else:
        response['connected'] = False
        response['name'] = 'Muhammad Ilham Peruzzi'
        html = 'lab_9/session/login.html'
        return render(request, html, response)

@csrf_exempt
def get_data_user_view(request):
    if request.method == "POST":
        npm = request.POST['npm']
        access_token = request.session['access_token']
        parameters = {"access_token": access_token, "client_id": get_client_id()}
        response = requests.get(API_MAHASISWA+npm, params=parameters)
        data = {'json':response.json()}
        return JsonResponse(data)

def get_friend_detail(request, friend_id):
    if 'user_login' not in request.session.keys():
        response['connected'] = False
        response['name'] = 'Muhammad Ilham Peruzzi'
        html = 'lab_9/session/login.html'
        return render(request, html, response)
    ## end of sol
    friend = Friend.objects.get(id=friend_id)
    response['friend'] = friend;
    html = 'lab_7/detail.html'
    return render(request, html, response)


@csrf_exempt
def data_friend(request):
	friend_list = Friend.objects.all()
	SomeModel_json = serializers.serialize("json", friend_list)
	data = {"json": SomeModel_json}
	return JsonResponse(data)

def friend_list(request):
    if 'user_login' not in request.session.keys():
        response['connected'] = False
        response['name'] = 'Muhammad Ilham Peruzzi'
        html = 'lab_9/session/login.html'
        return render(request, html, response)
    ## end of sol
    response['connected'] = True
    html = 'lab_7/daftar_teman.html'
    return render(request, html, response)

@csrf_exempt
def add_friend(request):
    if request.method == 'POST':
        name = request.POST['name']
        npm = request.POST['npm']
        alamat = request.POST['alamat']
        kode_pos = request.POST['kode_pos']
        kota_lahir = request.POST['kota_lahir']
        tanggal_lahir = request.POST['tanggal_lahir']
        friend_list = Friend.objects.all()
        is_taken = Friend.objects.filter(npm__iexact=npm).exists()
        if not is_taken:
        	friend = Friend(friend_name=name, npm=npm, alamat=alamat, kode_pos=kode_pos,kota_lahir=kota_lahir,tanggal_lahir=tanggal_lahir)
        	friend.save()
        	data = model_to_dict(friend)
        	return HttpResponse(data)

@csrf_exempt
def delete_friend(request, friend_id):
    Friend.objects.filter(id=friend_id).delete()
    data = {
        'status': 'ok'
    }
    return JsonResponse(data)

@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    data = {
        'is_taken': Friend.objects.filter(npm__iexact=npm).exists() #lakukan pengecekan apakah Friend dgn npm tsb sudah ada
    }
    return JsonResponse(data)

def model_to_dict(obj):
    data = serializers.serialize('json', [obj,])
    struct = json.loads(data)
    data = json.dumps(struct[0]["fields"])
    return data

lab_7/templates/lab_7/daftar_teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
    <section name="friend-list" id="friend-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2> Friends Fasilkom</h2>
                    <div id="friend-list" class="list-group">
                        
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block javascript %}
    <script>
        $( document ).ready(function () {
            $.ajax({
                method: "GET",
                url: '{% url "lab-7:data-friend" %}',
                success: function (response) {
                console.log(a)
                var a = response.json
                a = JSON.parse(a)


                for (var i = 0; i < a.length; i++) {
                    html = '<a class="list-group-item clearfix" href="get-friend-detail/'+a[i].pk+'" >' +a[i].fields.friend_name+" ("+a[i].fields.npm+')' +'<span data-id="'+a[i].pk+'" class="glyphicon glyphicon-remove" data-url="delete-friend/'+a[i].pk+'" style="color: red;position: absolute;top: 8px;right: 16px;"></span>'+'</a>';
                $("#friend-list").append(html)
                }
                
                    
                },
                error: function(error){
                    //#tampilkan pesan error
                    alert("Data kosong");
                }
            });


            $('#friend-list').on('click', '.list-group-item .glyphicon', function() {
                event.preventDefault();
                $(this).closest('.list-group-item').remove();
                $.ajax({
                method: "GET",
                url: $(this).data('url'),
                success: function (response) {
                },
                error: function(error){
                    //#tampilkan pesan error
                    alert("Data kosong");
                }
            });
            });


        });
    </script>
{% endblock %}

lab_7/templates/lab_7/detail.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
<h3 style="text-align: center;">Profile {{friend.friend_name}}</h3>
<br>
<table style="width:100%">
  <tr>
    <td><b>Nama</b></td>
    <td>{{friend.friend_name}}</td>
  </tr>
  <tr>
    <td><b>NPM</b></td>
    <td>{{friend.npm}}</td>
  </tr>
  <tr>
    <td><b>Alamat</b></td>
    <td id='alamat'>{{friend.alamat}}</td>
  </tr>
  <tr>
    <td><b>Kode Pos</b></td>
    <td>{{friend.kode_pos}}</td>
  </tr>
  <tr>
    <td><b>Kota Lahir</b></td>
    <td>{{friend.kota_lahir}}</td>
  </tr>
  <tr>
    <td><b>Tanggal Lahir</b></td>
    <td>{{friend.tanggal_lahir}}</td>
  </tr>
</table>
<h3>Peta Alamat</h3>
    <div id="map"></div>
{% endblock %}
{% block javascript %}
<script>
      var address = $("#alamat").text();
      console.log(address);
      var geocoder, map;
    window.initMap = function(){

		var geocoder = new google.maps.Geocoder();
		geocoder.geocode({'address': address}, function(results, status) {
			if (status === google.maps.GeocoderStatus.OK) {
				var propertiPeta = {
					center: results[0].geometry.location,
					zoom: 15,
					mapTypeId: google.maps.MapTypeId.ROADMAP
				};
				var peta = new google.maps.Map(document.getElementById("map"), propertiPeta);
				var marker = new google.maps.Marker({
				  map: peta,
				  position: results[0].geometry.location
				});
			} else {
				var html = '<div class="alert alert-danger text-center">Lokasi tidak ditemukan</div>';
                $("#map").append(html)
			}
		});
	}
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA0Xto4WmdHEV2AxHKGP4vrxVcn63NUyCc&callback=initMap" async defer></script>
   {% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                <div class="list-group" id="mahasiswa">
                    {% if mahasiswa_list %}
                        {% for mahasiswa in mahasiswa_list %}
                            <a class="list-group-item clearfix">
                                {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                <span class="pull-right">
                        <span class="btn btn-xs btn-default" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}', '{{ mahasiswa.alamat_mhs }}','{{ mahasiswa.kd_pos_mhs }}', '{{ mahasiswa.kota_lahir }}', '{{ mahasiswa.tgl_lahir }}')">

                            Tambah sebagai teman
                        </span>
                    </span>
                            </a>
                        {% endfor %}

                        
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada mahasiswa
                        </div>
                    {% endif %}
                </div>
                {% if mahasiswa_list.has_other_pages %}
  <ul class="pagination">
    {% if mahasiswa_list.has_previous %}
      <li><a href="?page={{ mahasiswa_list.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in mahasiswa_list.paginator.page_range %}
      {% if mahasiswa_list.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if mahasiswa_list.has_next %}
      <li><a href="?page={{ mahasiswa_list.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
            </div>
            <div class="col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ friend.friend_name }} ({{ friend.npm }})
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                    {% endif %}
                </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">npm</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>
                    <label for="field_name">name</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>
                    <button type="submit">Tambah</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block javascript %}
<script>

    $("#add-friend").on("submit", function () {
        name = $("#field_name").val()
        npm = $("#field_npm").val()
        if(name.length==0 || npm.length==0){
            alert("Mohon lengkapi data");
            event.preventDefault();
        }else{ 
            $.ajax({
                method: "POST",
                url: '{% url "lab-7:get-data-user" %}',
                data: {'npm':npm},
                dataType: 'json',
                success : function (response){
                    if(response.json.npm){
                        $("#field_name").val("");
                        $("#field_npm").val("");
                        addFriend(response.json.nama, response.json.npm, response.json.alamat_mhs,response.json.kd_pos_mhs,response.json.kota_lahir,response.json.tgl_lahir);
                        event.preventDefault();
                    }else{
                        alert("Mahasiswa tidak ditemukan");
                        $("#field_name").val("")
                        $("#field_npm").val("")
                        event.preventDefault();
                    }
                },
            });
            event.preventDefault();
        }
    });


    var addFriend = function(nama, npm, alamat,kode_pos,kota_lahir,tanggal_lahir) {
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:add-friend" %}',
            data: { 'name': nama, 'npm': npm, 'alamat':alamat,'kode_pos':kode_pos,'kota_lahir':kota_lahir,'tanggal_lahir':tanggal_lahir},
            success : function (friend) {
                friend = JSON.parse(friend)
                console.log(friend.friend_name)
                html = '<a class="list-group-item clearfix">' +friend.friend_name+" ("+friend.npm+')'+'</a>';
                $("#friend-list").append(html)
            },
            error : function (error) {
                alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
            }
        });
    };


    

    $("#field_npm").change(function () {
        console.log( $(this).val() );
        npm = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:validate-npm" %}',
            data: {
                'npm': npm
            },
            dataType: 'json',
            success: function (data) {
                console.log(data)
                if (data.is_taken) {
                    alert("Mahasiswa dengan npm seperti ini sudah ada");
                    $("#field_npm").val("")
                }
            }
        });
    });
</script>
{% endblock %}