LabPPW2017/LabPPW2017/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import lab02.urls as lab02
from lab02.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^lab02/', include(lab02, namespace='lab02')),
	url(r'^$', index),
]

lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_8/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_9/urls.py
from django.conf.urls import url
from .views import index, profile,add_session_drones, del_session_drones, clear_session_drones,cookie_login, cookie_auth_login, cookie_profile, cookie_clear

# sol to challenge
from .views import add_session_item, del_session_item, clear_session_item
# /sol
from .custom_auth import auth_login, auth_logout

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^profile/$', profile, name='profile'),

    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),

    #add/delete drones
    url(r'^add_session_drones/(?P<id>\d+)/$', add_session_drones, name='add_session_drones'),
    url(r'^del_session_drones/(?P<id>\d+)/$', del_session_drones, name='del_session_drones'),
    url(r'^clear_session_drones/$', clear_session_drones, name='clear_session_drones'),

    # cookie
    url(r'^cookie/login/$', cookie_login, name='cookie_login'),
    url(r'^cookie/auth_login/$', cookie_auth_login, name='cookie_auth_login'),
    url(r'^cookie/profile/$', cookie_profile, name='cookie_profile'),
    url(r'^cookie/clear/$', cookie_clear, name='cookie_clear'), #sekaligus logout dari cookie

    #general function : solution to challenge
    url(r'^add_session_item/(?P<key>\w+)/(?P<id>\d+)/$', add_session_item, name='add_session_item'),
    url(r'^del_session_item/(?P<key>\w+)/(?P<id>\d+)/$', del_session_item, name='del_session_item'),
    url(r'^clear_session_item/(?P<key>\w+)/$', clear_session_item, name='clear_session_item'),


]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
from lab_4.views import index
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
	url(r'^lab-2/', include(lab_2,namespace='lab-2')),
	url(r'^lab-2-addon/', include(lab_2_addon,namespace='lab-2-addon')),
	url(r'^$',RedirectView.as_view(url='/lab-4/',permanent='true'),name='index'),
	url(r'^lab-3/', include(lab_3,namespace='lab-3')),
    url(r'^lab-4/', include(lab_4, namespace='lab-4')),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    url(r'^lab-8/', include(lab_8, namespace='lab-8')),
    url(r'^lab-9/', include(lab_9, namespace='lab-9')),
    url(r'^lab-10/', include(lab_10, namespace='lab-10')),
]

lab_8/models.py
from django.db import models

# Create your models here.

lab_8/views.py
from django.shortcuts import render

response={}
def index(request):
	if 'user_login' in request.session:
		response['author'] = request.session['user_login']
		response['kode_identitas'] = request.session['kode_identitas']
		response['connected'] = True
		response['name'] = 'Muhammad Ilham Peruzzi'
		html = 'lab_8/lab_8.html'
		return render(request, html, response)
	else:
		response['connected'] = False
		response['name'] = 'Muhammad Ilham Peruzzi'
		html = 'lab_9/session/login.html'
		return render(request, html, response)

lab_8/templates/lab_8/partials/footer.html
<div class="panel-footer footer">
  <p id='footer' style="color: black">Made with Love by &copy; {{name}}</p>
</div>

lab_8/templates/lab_8/partials/header.html
<!-- templates/lab_5/partials/header.html -->
<nav class="navbar navbar-default navbar-static-top navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        
      </button>
      <a class="navbar-brand" href="{% url 'lab-8:index' %}">Home</a>
    </div>
    {% if connected %}
     <a style="margin-top: 10px" href="{% url 'lab-9:auth_logout' %}" class="btn btn-danger pull-right" onclick="return confirm('Keluar?')">
            Logout </a><p class="navbar-text pull-right">Anda Masuk sebagai : {{author}} ({{kode_identitas}})</p>
    {% endif %}
    <div id="navbar" class="navbar-collapse collapse">
      
    </div><!--/.nav-collapse -->
  </div>
</nav>